
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.mineterra.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.mineterra.item.WoodStaffItem;
import net.mcreator.mineterra.item.WoodKatanaItem;
import net.mcreator.mineterra.item.VampiricInstinctItem;
import net.mcreator.mineterra.item.TitaniumSwordItem;
import net.mcreator.mineterra.item.TitaniumShovelItem;
import net.mcreator.mineterra.item.TitaniumPickaxeItem;
import net.mcreator.mineterra.item.TitaniumIngotItem;
import net.mcreator.mineterra.item.TitaniumHoeItem;
import net.mcreator.mineterra.item.TitaniumAxeItem;
import net.mcreator.mineterra.item.TitaniumArmorItem;
import net.mcreator.mineterra.item.SuradiirsScytheItem;
import net.mcreator.mineterra.item.SuddenBurstItem;
import net.mcreator.mineterra.item.StormrazorKatanaItem;
import net.mcreator.mineterra.item.StoneKatanaItem;
import net.mcreator.mineterra.item.StoneDaggerItem;
import net.mcreator.mineterra.item.SteelSwordItem;
import net.mcreator.mineterra.item.SteelShovelItem;
import net.mcreator.mineterra.item.SteelScytheItem;
import net.mcreator.mineterra.item.SteelRapierItem;
import net.mcreator.mineterra.item.SteelPickaxeItem;
import net.mcreator.mineterra.item.SteelIngotItem;
import net.mcreator.mineterra.item.SteelHoeItem;
import net.mcreator.mineterra.item.SteelAxeItem;
import net.mcreator.mineterra.item.SteelArmorItem;
import net.mcreator.mineterra.item.StaffOfLesserMagicItem;
import net.mcreator.mineterra.item.SpiritualLongswordItem;
import net.mcreator.mineterra.item.SilverSwordItem;
import net.mcreator.mineterra.item.SilverIngotItem;
import net.mcreator.mineterra.item.SilverDaggerItem;
import net.mcreator.mineterra.item.SacrificeDaggerItem;
import net.mcreator.mineterra.item.RustedIronScytheItem;
import net.mcreator.mineterra.item.RunicStoneResistenceItem;
import net.mcreator.mineterra.item.RunicStonePrecisionItem;
import net.mcreator.mineterra.item.RunicStoneFatalityItem;
import net.mcreator.mineterra.item.RunicStoneDuelingItem;
import net.mcreator.mineterra.item.RunicStoneBrutalityItem;
import net.mcreator.mineterra.item.RuneStoneSpellcasterItem;
import net.mcreator.mineterra.item.NetheriteSaiItem;
import net.mcreator.mineterra.item.NetheriteKatanaItem;
import net.mcreator.mineterra.item.NetheriteDaggerItem;
import net.mcreator.mineterra.item.NetheriteClaymoreItem;
import net.mcreator.mineterra.item.NebulousVeilDaggerItem;
import net.mcreator.mineterra.item.MagicalCasingItem;
import net.mcreator.mineterra.item.LightStaffItem;
import net.mcreator.mineterra.item.LightOrbItem;
import net.mcreator.mineterra.item.LightIronDaggerItem;
import net.mcreator.mineterra.item.IronScytheItem;
import net.mcreator.mineterra.item.IronSaiItem;
import net.mcreator.mineterra.item.IronRapierItem;
import net.mcreator.mineterra.item.IronKatanaItem;
import net.mcreator.mineterra.item.IronDaggerItem;
import net.mcreator.mineterra.item.IronClaymoreItem;
import net.mcreator.mineterra.item.ImperialGoldClaymoreItem;
import net.mcreator.mineterra.item.GoldenClaymoreItem;
import net.mcreator.mineterra.item.GoldSaiItem;
import net.mcreator.mineterra.item.GoldRapierItem;
import net.mcreator.mineterra.item.GoldKatanaItem;
import net.mcreator.mineterra.item.GoldDaggerItem;
import net.mcreator.mineterra.item.ForgeHammerItem;
import net.mcreator.mineterra.item.FocusBladeItem;
import net.mcreator.mineterra.item.FlintDaggerItem;
import net.mcreator.mineterra.item.FireStaffItem;
import net.mcreator.mineterra.item.EmptyItem;
import net.mcreator.mineterra.item.ElderlySaiItem;
import net.mcreator.mineterra.item.DragonBiteDaggerItem;
import net.mcreator.mineterra.item.DiamondSaiItem;
import net.mcreator.mineterra.item.DiamondRapierItem;
import net.mcreator.mineterra.item.DiamondKatanaItem;
import net.mcreator.mineterra.item.DiamondDaggerItem;
import net.mcreator.mineterra.item.DiamondClaymoreItem;
import net.mcreator.mineterra.item.DemonitaSwordItem;
import net.mcreator.mineterra.item.DemonitaItem;
import net.mcreator.mineterra.item.DashItem;
import net.mcreator.mineterra.item.CrepitarsBladeSwordItem;
import net.mcreator.mineterra.item.CopperSwordItem;
import net.mcreator.mineterra.item.CelestiumSwordItem;
import net.mcreator.mineterra.item.CelestiumIngotItem;
import net.mcreator.mineterra.item.BladeOfBanishedQueenItem;
import net.mcreator.mineterra.item.BalsadurGreatswordItem;
import net.mcreator.mineterra.item.ArcanitiumItem;
import net.mcreator.mineterra.item.ArcaniteSwordItem;
import net.mcreator.mineterra.item.ArcaniteItem;
import net.mcreator.mineterra.item.ArcaniteGemstoneItem;
import net.mcreator.mineterra.item.ArcaneTopazItem;
import net.mcreator.mineterra.item.AmethystSwordItem;
import net.mcreator.mineterra.MineterraMod;

public class MineterraModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, MineterraMod.MODID);
	public static final RegistryObject<Item> STONE_DAGGER = REGISTRY.register("stone_dagger", () -> new StoneDaggerItem());
	public static final RegistryObject<Item> IRON_DAGGER = REGISTRY.register("iron_dagger", () -> new IronDaggerItem());
	public static final RegistryObject<Item> SILVER_DAGGER = REGISTRY.register("silver_dagger", () -> new SilverDaggerItem());
	public static final RegistryObject<Item> GOLD_DAGGER = REGISTRY.register("gold_dagger", () -> new GoldDaggerItem());
	public static final RegistryObject<Item> DIAMOND_DAGGER = REGISTRY.register("diamond_dagger", () -> new DiamondDaggerItem());
	public static final RegistryObject<Item> NETHERITE_DAGGER = REGISTRY.register("netherite_dagger", () -> new NetheriteDaggerItem());
	public static final RegistryObject<Item> SACRIFICE_DAGGER = REGISTRY.register("sacrifice_dagger", () -> new SacrificeDaggerItem());
	public static final RegistryObject<Item> FLINT_DAGGER = REGISTRY.register("flint_dagger", () -> new FlintDaggerItem());
	public static final RegistryObject<Item> NEBULOUS_VEIL_DAGGER = REGISTRY.register("nebulous_veil_dagger", () -> new NebulousVeilDaggerItem());
	public static final RegistryObject<Item> DRAGON_BITE_DAGGER = REGISTRY.register("dragon_bite_dagger", () -> new DragonBiteDaggerItem());
	public static final RegistryObject<Item> IRON_SAI_RAPIER = REGISTRY.register("iron_sai_rapier", () -> new IronSaiItem());
	public static final RegistryObject<Item> ELDERLY_RAPIER_SAI = REGISTRY.register("elderly_rapier_sai", () -> new ElderlySaiItem());
	public static final RegistryObject<Item> GOLD_SAI_RAPIER = REGISTRY.register("gold_sai_rapier", () -> new GoldSaiItem());
	public static final RegistryObject<Item> DIAMOND_SAI_RAPIER = REGISTRY.register("diamond_sai_rapier", () -> new DiamondSaiItem());
	public static final RegistryObject<Item> NETHERITE_SAI_RAPIER = REGISTRY.register("netherite_sai_rapier", () -> new NetheriteSaiItem());
	public static final RegistryObject<Item> IRON_CLAYMORE = REGISTRY.register("iron_claymore", () -> new IronClaymoreItem());
	public static final RegistryObject<Item> GOLDEN_CLAYMORE = REGISTRY.register("golden_claymore", () -> new GoldenClaymoreItem());
	public static final RegistryObject<Item> DIAMOND_CLAYMORE = REGISTRY.register("diamond_claymore", () -> new DiamondClaymoreItem());
	public static final RegistryObject<Item> CREPITARS_BLADE_SWORD = REGISTRY.register("crepitars_blade_sword", () -> new CrepitarsBladeSwordItem());
	public static final RegistryObject<Item> NETHERITE_CLAYMORE = REGISTRY.register("netherite_claymore", () -> new NetheriteClaymoreItem());
	public static final RegistryObject<Item> IMPERIAL_GOLD_CLAYMORE = REGISTRY.register("imperial_gold_claymore", () -> new ImperialGoldClaymoreItem());
	public static final RegistryObject<Item> SPIRITUAL_CLAYMORE = REGISTRY.register("spiritual_claymore", () -> new SpiritualLongswordItem());
	public static final RegistryObject<Item> RAPIER = REGISTRY.register("rapier", () -> new IronRapierItem());
	public static final RegistryObject<Item> WOOD_KATANA = REGISTRY.register("wood_katana", () -> new WoodKatanaItem());
	public static final RegistryObject<Item> STORMRAZOR_KATANA = REGISTRY.register("stormrazor_katana", () -> new StormrazorKatanaItem());
	public static final RegistryObject<Item> STONE_KATANA = REGISTRY.register("stone_katana", () -> new StoneKatanaItem());
	public static final RegistryObject<Item> GOLD_KATANA = REGISTRY.register("gold_katana", () -> new GoldKatanaItem());
	public static final RegistryObject<Item> IRON_KATANA = REGISTRY.register("iron_katana", () -> new IronKatanaItem());
	public static final RegistryObject<Item> DIAMOND_KATANA = REGISTRY.register("diamond_katana", () -> new DiamondKatanaItem());
	public static final RegistryObject<Item> NETHERITE_KATANA = REGISTRY.register("netherite_katana", () -> new NetheriteKatanaItem());
	public static final RegistryObject<Item> TITANIUM_SWORD = REGISTRY.register("titanium_sword", () -> new TitaniumSwordItem());
	public static final RegistryObject<Item> WOOD_STAFF = REGISTRY.register("wood_staff", () -> new WoodStaffItem());
	public static final RegistryObject<Item> ARCANITE_STAFF_WAND = REGISTRY.register("arcanite_staff_wand", () -> new StaffOfLesserMagicItem());
	public static final RegistryObject<Item> LIGHT_STAFF_WAND = REGISTRY.register("light_staff_wand", () -> new LightStaffItem());
	public static final RegistryObject<Item> FIRE_STAFF_WAND = REGISTRY.register("fire_staff_wand", () -> new FireStaffItem());
	public static final RegistryObject<Item> LIGHT_IRON_DAGGER = REGISTRY.register("light_iron_dagger", () -> new LightIronDaggerItem());
	public static final RegistryObject<Item> CELESTIUM_SWORD = REGISTRY.register("celestium_sword", () -> new CelestiumSwordItem());
	public static final RegistryObject<Item> ARCANITE_SWORD = REGISTRY.register("arcanite_sword", () -> new ArcaniteSwordItem());
	public static final RegistryObject<Item> BLADE_OF_BANISHED_QUEEN = REGISTRY.register("blade_of_banished_queen", () -> new BladeOfBanishedQueenItem());
	public static final RegistryObject<Item> STEEL_SWORD = REGISTRY.register("steel_sword", () -> new SteelSwordItem());
	public static final RegistryObject<Item> DEMONITA_SWORD = REGISTRY.register("demonita_sword", () -> new DemonitaSwordItem());
	public static final RegistryObject<Item> SILVER_SWORD = REGISTRY.register("silver_sword", () -> new SilverSwordItem());
	public static final RegistryObject<Item> COPPER_SWORD = REGISTRY.register("copper_sword", () -> new CopperSwordItem());
	public static final RegistryObject<Item> SURADIIRS_SCYTHE = REGISTRY.register("suradiirs_scythe", () -> new SuradiirsScytheItem());
	public static final RegistryObject<Item> IRON_SCYTHE = REGISTRY.register("iron_scythe", () -> new IronScytheItem());
	public static final RegistryObject<Item> STEEL_SCYTHE = REGISTRY.register("steel_scythe", () -> new SteelScytheItem());
	public static final RegistryObject<Item> RUSTED_IRON_SCYTHE = REGISTRY.register("rusted_iron_scythe", () -> new RustedIronScytheItem());
	public static final RegistryObject<Item> GOLD_RAPIER = REGISTRY.register("gold_rapier", () -> new GoldRapierItem());
	public static final RegistryObject<Item> DIAMOND_RAPIER = REGISTRY.register("diamond_rapier", () -> new DiamondRapierItem());
	public static final RegistryObject<Item> STEEL_RAPIER = REGISTRY.register("steel_rapier", () -> new SteelRapierItem());
	public static final RegistryObject<Item> BALSADUR_GREATSWORD_CLAYMORE = REGISTRY.register("balsadur_greatsword_claymore", () -> new BalsadurGreatswordItem());
	public static final RegistryObject<Item> TITANIUM_ARMOR_HELMET = REGISTRY.register("titanium_armor_helmet", () -> new TitaniumArmorItem.Helmet());
	public static final RegistryObject<Item> TITANIUM_ARMOR_CHESTPLATE = REGISTRY.register("titanium_armor_chestplate", () -> new TitaniumArmorItem.Chestplate());
	public static final RegistryObject<Item> TITANIUM_ARMOR_LEGGINGS = REGISTRY.register("titanium_armor_leggings", () -> new TitaniumArmorItem.Leggings());
	public static final RegistryObject<Item> TITANIUM_ARMOR_BOOTS = REGISTRY.register("titanium_armor_boots", () -> new TitaniumArmorItem.Boots());
	public static final RegistryObject<Item> STEEL_ARMOR_HELMET = REGISTRY.register("steel_armor_helmet", () -> new SteelArmorItem.Helmet());
	public static final RegistryObject<Item> STEEL_ARMOR_CHESTPLATE = REGISTRY.register("steel_armor_chestplate", () -> new SteelArmorItem.Chestplate());
	public static final RegistryObject<Item> STEEL_ARMOR_LEGGINGS = REGISTRY.register("steel_armor_leggings", () -> new SteelArmorItem.Leggings());
	public static final RegistryObject<Item> STEEL_ARMOR_BOOTS = REGISTRY.register("steel_armor_boots", () -> new SteelArmorItem.Boots());
	public static final RegistryObject<Item> FORGE_HAMMER = REGISTRY.register("forge_hammer", () -> new ForgeHammerItem());
	public static final RegistryObject<Item> TITANIUM_PICKAXE = REGISTRY.register("titanium_pickaxe", () -> new TitaniumPickaxeItem());
	public static final RegistryObject<Item> TITANIUM_AXE = REGISTRY.register("titanium_axe", () -> new TitaniumAxeItem());
	public static final RegistryObject<Item> TITANIUM_SHOVEL = REGISTRY.register("titanium_shovel", () -> new TitaniumShovelItem());
	public static final RegistryObject<Item> TITANIUM_HOE = REGISTRY.register("titanium_hoe", () -> new TitaniumHoeItem());
	public static final RegistryObject<Item> STEEL_PICKAXE = REGISTRY.register("steel_pickaxe", () -> new SteelPickaxeItem());
	public static final RegistryObject<Item> STEEL_AXE = REGISTRY.register("steel_axe", () -> new SteelAxeItem());
	public static final RegistryObject<Item> STEEL_SHOVEL = REGISTRY.register("steel_shovel", () -> new SteelShovelItem());
	public static final RegistryObject<Item> STEEL_HOE = REGISTRY.register("steel_hoe", () -> new SteelHoeItem());
	public static final RegistryObject<Item> DEMONITA_ORE = block(MineterraModBlocks.DEMONITA_ORE);
	public static final RegistryObject<Item> DEMONITA_BLOCK = block(MineterraModBlocks.DEMONITA_BLOCK);
	public static final RegistryObject<Item> DEMONITA = REGISTRY.register("demonita", () -> new DemonitaItem());
	public static final RegistryObject<Item> TITANIUM_ORE = block(MineterraModBlocks.TITANIUM_ORE);
	public static final RegistryObject<Item> TITANIUM_BLOCK = block(MineterraModBlocks.TITANIUM_BLOCK);
	public static final RegistryObject<Item> TITANIUM_INGOT = REGISTRY.register("titanium_ingot", () -> new TitaniumIngotItem());
	public static final RegistryObject<Item> MAGICAL_CASING = REGISTRY.register("magical_casing", () -> new MagicalCasingItem());
	public static final RegistryObject<Item> EMPTY = REGISTRY.register("empty", () -> new EmptyItem());
	public static final RegistryObject<Item> ARCANITIUM_ORE = block(MineterraModBlocks.ARCANITIUM_ORE);
	public static final RegistryObject<Item> ARCANITIUM_BLOCK = block(MineterraModBlocks.ARCANITIUM_BLOCK);
	public static final RegistryObject<Item> ARCANITIUM = REGISTRY.register("arcanitium", () -> new ArcanitiumItem());
	public static final RegistryObject<Item> ARCANITE = REGISTRY.register("arcanite", () -> new ArcaniteItem());
	public static final RegistryObject<Item> ARCANE_TOPAZ = REGISTRY.register("arcane_topaz", () -> new ArcaneTopazItem());
	public static final RegistryObject<Item> ARCANITE_GEMSTONE = REGISTRY.register("arcanite_gemstone", () -> new ArcaniteGemstoneItem());
	public static final RegistryObject<Item> STEEL_BLOCK = block(MineterraModBlocks.STEEL_BLOCK);
	public static final RegistryObject<Item> STEEL_INGOT = REGISTRY.register("steel_ingot", () -> new SteelIngotItem());
	public static final RegistryObject<Item> RUNIC_STONE_PRECISION = REGISTRY.register("runic_stone_precision", () -> new RunicStonePrecisionItem());
	public static final RegistryObject<Item> RUNIC_STONE_DUELING = REGISTRY.register("runic_stone_dueling", () -> new RunicStoneDuelingItem());
	public static final RegistryObject<Item> RUNIC_STONE_RESISTENCE = REGISTRY.register("runic_stone_resistence", () -> new RunicStoneResistenceItem());
	public static final RegistryObject<Item> RUNIC_STONE_FATALITY = REGISTRY.register("runic_stone_fatality", () -> new RunicStoneFatalityItem());
	public static final RegistryObject<Item> RUNIC_STONE_BRUTALITY = REGISTRY.register("runic_stone_brutality", () -> new RunicStoneBrutalityItem());
	public static final RegistryObject<Item> RUNE_STONE_SPELLCASTER = REGISTRY.register("rune_stone_spellcaster", () -> new RuneStoneSpellcasterItem());
	public static final RegistryObject<Item> CELESTIUM_ORE = block(MineterraModBlocks.CELESTIUM_ORE);
	public static final RegistryObject<Item> CELESTIUM_BLOCK = block(MineterraModBlocks.CELESTIUM_BLOCK);
	public static final RegistryObject<Item> CELESTIUM_INGOT = REGISTRY.register("celestium_ingot", () -> new CelestiumIngotItem());
	public static final RegistryObject<Item> DASH = REGISTRY.register("dash", () -> new DashItem());
	public static final RegistryObject<Item> FOCUS_BLADE = REGISTRY.register("focus_blade", () -> new FocusBladeItem());
	public static final RegistryObject<Item> VAMPIRIC_INSTINCT = REGISTRY.register("vampiric_instinct", () -> new VampiricInstinctItem());
	public static final RegistryObject<Item> SUDDEN_BURST = REGISTRY.register("sudden_burst", () -> new SuddenBurstItem());
	public static final RegistryObject<Item> SILVER_INGOT = REGISTRY.register("silver_ingot", () -> new SilverIngotItem());
	public static final RegistryObject<Item> SILVER_ORE = block(MineterraModBlocks.SILVER_ORE);
	public static final RegistryObject<Item> SILVER_BLOCK = block(MineterraModBlocks.SILVER_BLOCK);
	public static final RegistryObject<Item> LIGHT_ORB = REGISTRY.register("light_orb", () -> new LightOrbItem());
	public static final RegistryObject<Item> AMETHYST_SWORD = REGISTRY.register("amethyst_sword", () -> new AmethystSwordItem());

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
